// <auto-generated />
using System;
using AbOvo.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AbOvo.Api.Persistence.Migrations
{
    [DbContext(typeof(AbOvoDbContext))]
    [Migration("20260920120000_AddReaderPreference")]
    partial class AddReaderPreference
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AbOvo.Api.Persistence.FrameOutcome", b =>
                {
                    b.Property<string>("BundleTag")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Track")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Unit")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Step")
                        .HasColumnType("integer");

                    b.Property<string>("Check")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.HasKey("BundleTag", "Track", "Unit", "Step", "Check", "Attempt", "Passed");

                    b.HasIndex("BundleTag", "Track", "Unit", "Step");

                    b.ToTable("FrameOutcomes");
                });

            modelBuilder.Entity("AbOvo.Api.Persistence.ReaderPreference", b =>
                {
                    b.Property<string>("Subject")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Subject");

                    b.ToTable("ReaderPreferences");
                });

            modelBuilder.Entity("AbOvo.Api.Persistence.ReaderProgress", b =>
                {
                    b.Property<string>("Subject")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Track")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Unit")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Step")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Subject", "Track", "Unit");

                    b.ToTable("ReaderProgress");
                });
#pragma warning restore 612, 618
        }
    }
}
