namespace AbOvo.Seed;

/// <summary>
/// One example account this seeder makes, and what it is FOR.
/// </summary>
/// <param name="Email">
/// Always under <c>.test</c>, which RFC 2606 reserves and no resolver will ever answer for.
/// The acceptance suite's fixture accounts use the same convention for the same reason: an
/// address that cannot receive mail cannot become a real account by accident, and cannot be
/// somebody's.
/// </param>
/// <param name="Roles">
/// Granted after registration, because <c>POST /api/v1/auth/register</c> assigns none —
/// authservice's own <c>DbSeeder</c> creates the three role rows and nothing else.
/// </param>
/// <param name="Purpose">Printed beside the account, so the log says why it exists.</param>
internal sealed record ExampleReader(string Email, string[] Roles, string Purpose);

/// <summary>
/// The accounts a local machine gets, and the reason the list is exactly this long.
///
/// <para>
/// ONE PER ROLE SHAPE THE PRODUCT ACTUALLY DISTINGUISHES, and no more. `AbOvo.Api` declares
/// three authorization groups in its composition root — anonymous, authenticated, and
/// <c>RequireRole("Admin", "SuperAdmin")</c> — so a set of example accounts that cannot
/// reach all three leaves part of the system unreachable from a fresh clone, which is the
/// complaint this seeder answers. A fourth account would demonstrate nothing a reviewer
/// cannot already see.
/// </para>
///
/// <para>
/// NO PASSWORD IS DECLARED HERE. It arrives from the environment, generated by the AppHost
/// and persisted to <c>dotnet user-secrets</c> (P5, and AGENTS.md's "no secret is ever a
/// literal, anywhere"). The acceptance suite's <c>fixtures/accounts.mts</c> is allowed its
/// literal because nothing has ever accepted it; these accounts are accepted by a running
/// identity service, which makes their password a credential rather than a fixture value.
/// </para>
/// </summary>
internal static class ExampleReaders
{
    /// <summary>The role `AbOvo.Api`'s admin group accepts, beside SuperAdmin.</summary>
    internal const string AuthorRole = "Admin";

    internal static readonly ExampleReader[] All =
    [
        new ExampleReader(
            "reader@ab-ovo.test",
            [],
            "an ordinary reader: progress syncs, the admin views are refused"),
        new ExampleReader(
            "author@ab-ovo.test",
            [AuthorRole],
            "the author's view: /instrument's ranked list, which the admin group gates"),
    ];
}
